const constants = {
    LISTAR_RECEBIMENTOS: "LISTAR_RECEBIMENTOS",
    LISTAR_PAGAMENTOS: "LISTAR_PAGAMENTOS",
    LISTAR_CAIXA: "LISTAR_CAIXA",
    INSERIR_RECEBIMENTO: "INSERIR_RECEBIMENTO",
    INSERIR_PAGAMENTO: "INSERIR_PAGAMENTO",
    INSERIR_PAGAMENTO_DUPLICADA: "INSERIR_PAGAMENTO_DUPLICADA",
    EDITAR_RECEBIMENTO: "EDITAR_RECEBIMENTO",
    EDITAR_PAGAMENTO: "EDITAR_PAGAMENTO"
};

export default constants;